version: '3.3'

services:
  shard1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: shard1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'PeopleShard'
      MYSQL_USER: 'stud1'
      MYSQL_PASSWORD: 'stud'
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - mai-network
    ports:
      - 3360:3306
    volumes:
      - shard1-data:/var/lib/mysql

  shard2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: shard2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'PeopleShard'
      MYSQL_USER: 'stud1'
      MYSQL_PASSWORD: 'stud'
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - mai-network
    ports:
      - 3361:3306
    volumes:
      - shard2-data:/var/lib/mysql
  
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    depends_on:
      - "shard1"
      - "shard2"
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    networks:
      - mai-network
    ports:
      - "6033:6033"
      - "6032:6032"

volumes:
  shard1-data:
  shard2-data:
  proxysql-data:

networks:
  mai-network:
    driver: "bridge"
    external: false
